// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var mapDefine = MapDefine.FromJson(jsonString);

namespace QuickType
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class MapDefine
    {
        [JsonProperty("compressionlevel")]
        public int Compressionlevel { get; set; }

        [JsonProperty("height")]
        public int Height { get; set; }

        [JsonProperty("infinite")]
        public bool Infinite { get; set; }

        [JsonProperty("layers")]
        public Layer[] Layers { get; set; }

        [JsonProperty("nextlayerid")]
        public int Nextlayerid { get; set; }

        [JsonProperty("nextobjectid")]
        public int Nextobjectid { get; set; }

        [JsonProperty("orientation")]
        public string Orientation { get; set; }

        [JsonProperty("renderorder")]
        public string Renderorder { get; set; }

        [JsonProperty("tiledversion")]
        public string Tiledversion { get; set; }

        [JsonProperty("tileheight")]
        public int Tileheight { get; set; }

        [JsonProperty("tilesets")]
        public Tileset[] Tilesets { get; set; }

        [JsonProperty("tilewidth")]
        public int Tilewidth { get; set; }

        [JsonProperty("type")]
        public string Type { get; set; }

        [JsonProperty("version")]
        public double Version { get; set; }

        [JsonProperty("width")]
        public int Width { get; set; }
    }

    public partial class Layer
    {
        [JsonProperty("data")]
        public int[] Data { get; set; }

        [JsonProperty("height")]
        public int Height { get; set; }

        [JsonProperty("id")]
        public int Id { get; set; }

        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("opacity")]
        public int Opacity { get; set; }

        [JsonProperty("type")]
        public string Type { get; set; }

        [JsonProperty("visible")]
        public bool Visible { get; set; }

        [JsonProperty("width")]
        public int Width { get; set; }

        [JsonProperty("x")]
        public int X { get; set; }

        [JsonProperty("y")]
        public int Y { get; set; }
    }

    public partial class Tileset
    {
        [JsonProperty("firstgid")]
        public int Firstgid { get; set; }

        [JsonProperty("source")]
        public string Source { get; set; }
    }

    public partial class MapDefine
    {
        public static MapDefine FromJson(string json) => JsonConvert.DeserializeObject<MapDefine>(json, QuickType.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this MapDefine self) => JsonConvert.SerializeObject(self, QuickType.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
